// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jlsjmkxznbxirvyltmuf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impsc2pta3h6bmJ4aXJ2eWx0bXVmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwMDEwMDIsImV4cCI6MjA2MzU3NzAwMn0.ijNQTNb1O9MnJI5wFmTZLfex4F3zpoUTA25H3bx-wlI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);